Repository AY2425S1-CS2103T-T13-1/tp, pull requests merged in 2024-11, with the labels that each got.

#90 Fix command example messages
  src/main/java/seedu/address/logic/commands/AddEmergencyContactCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: severity.Low

#97 Move result display box to occupy left half of the app
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.High, severity.Medium, alpha-bug

#94 Fix documentation bugs
  docs/DeveloperGuide.md
  docs/diagrams/FindSequenceDiagram.puml
Labels: priority.High, alpha-bug

#113 Fix spacing issue in Edit Command
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: alpha-bug

#112 Update UG link in Help window
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.High, alpha-bug

#117 Update user guide
  docs/UserGuide.md
  docs/images/Quickstart-new-terminal.png
  docs/images/findAlexDavidResult.png
  docs/images/findDavRoyResult.png
  docs/images/finddocZhouResult.png
  docs/images/uitutorial.png
  docs/index.md
Labels: type.Chore, alpha-bug

#116 Fix emergency contact card UI bugs
  src/main/java/seedu/address/logic/commands/AddEmergencyContactCommand.java
  src/main/java/seedu/address/model/person/EmergencyContact.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/EmergencyContactListPanel.java
  src/main/java/seedu/address/ui/EmergencyContactSelectionController.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: priority.Medium

#118 Add sorting functionality for list command
  docs/Gemfile.lock
  src/main/java/seedu/address/logic/commands/DeleteArchiveCommand.java
  src/main/java/seedu/address/logic/commands/ListArchiveFilesCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/LoadArchiveCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ListCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/PersonComparators.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Enhancement, priority.Medium

#83 Fix visual bugs
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.Bug, priority.High, severity.Medium

#119 Update Documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/finddoc-tan-ed.png
  docs/images/helpMessage.png
  docs/images/helpWindow.png
  docs/images/uitutorial.png
Labels: type.Chore, alpha-bug

#127 Change archive timestamp to ISO datetime format
  src/main/java/seedu/address/logic/commands/DeleteArchiveCommand.java
  src/main/java/seedu/address/logic/commands/LoadArchiveCommand.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Enhancement, priority.Medium

#128 Add icons for patient details
  src/main/resources/images/address.png
  src/main/resources/images/doctor.png
  src/main/resources/images/mail.png
  src/main/resources/images/phone.png
  src/main/resources/images/relationship.png
  src/main/resources/view/EmergencyContactListCard.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: priority.Medium

#135 Fix relationship bugs
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/person/Relationship.java
Labels: severity.Medium, alpha-bug

#131 Fix more bugs
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.Bug, priority.High, alpha-bug

#136 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/PersonClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: type.Chore, alpha-bug

#139 Separate Error Message for Undo & Redo command
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.Bug, alpha-bug

#143 Update diagrams and use cases in DG
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DoctorClassDiagram.puml
  docs/diagrams/EmergencyContactClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PersonClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/PersonClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: type.Chore, alpha-bug

#145 Fix Bug where delete index is never shown as overshadowed by delete a…
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.Bug, alpha-bug

#144 Improve readability of status msg
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/model/person/EmergencyContact.java
Labels: alpha-bug

#146 Update UI image on homepage
  docs/UserGuide.md
  docs/index.md
Labels: type.Chore, priority.Medium

#149 Autcommand fix
  src/main/java/seedu/address/ui/CommandBox.java
Labels: alpha-bug

#213 Fixed all Dry PE bugs related to Suggestion Feature
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/resources/view/CommandBox.fxml
Labels: type.Bug

#216 Add Autocomplete
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.Bug, severity.High

#235 UG update
  docs/UserGuide.md
  docs/images/red_autocomplete.png
  docs/images/similarprefix.png
Labels: type.Bug, type.Chore, severity.VeryLow, type.Enhancement, type.Epic, priority.High, priority.Medium, type.Story, priority.Low, severity.Low, severity.Medium, severity.High, alpha-bug, future-work
